on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    steps:
      - name: delete-package
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'publish-packages/game'
          package-type: 'container'
          min-versions-to-keep: 1
          token: ${{ secrets.GITHUB_TOKEN }}
        
