on:
  schedule:
    - cron: '0/6 13 * * *'
  workflow_dispatch:

permissions:
  packages: write
  contents: read
 
jobs:
  delete-old-packages-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-name:
          - 'publish-packages/game'
          - 'publish-packages/game'
    steps:
      - name: delete-package
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.package-name }}
          package-type: 'container'
          min-versions-to-keep: 5
          token: ${{ secrets.GITHUB_TOKEN }}
